### PR TITLE
Consolidate imagine generation commands #76

### PR DESCRIPTION
**Pull request by mishalhossin**

### CODE REVIEW

**Comment by mak448a** [comment]
Thanks! I’ll check it out later.

**Comment by mak448a** [comment]
Hm. Did you import this from the wrong module? I'm not an expert in the class names, so I'm not quite sure how to fix it.
```
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.commands_cogs.generative_image' raised an error: AttributeError: 'HybridGroup' object has no attribute 'hybrid_command'
```

**Comment by mak448a** [comment]
Never mind. I fixed it.

**Comment by mishalhossin** [comment]
oops

**Comment by mak448a** [comment]
Well, I guess I can do this later. Closing

**Pull request closed without merging**
